services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-example}
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo_data:/data/db
    networks:
      - uncovering-history
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD:-example}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-example}@mongo:27017/${MONGO_DBNAME:-example}?authSource=admin&retryWrites=false
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    networks:
      - uncovering-history
  api:
    build:
      context: ./  
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.docker/uploads:/app/uploads
    ports:
      - "8082:8080"    # ðŸ”¥ PORTA AJUSTADA AQUI
    depends_on:
      - mongo
    command: "tail -f /dev/null"
    environment:
      - MONGO_USER=${MONGO_USER:-root}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-example}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_DBNAME:-example}
      - SECRET_TOKEN=${SECRET_TOKEN:-supersecret}
      - MONGODB_URI=mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-example}@mongo:27017/${MONGO_DBNAME:-example}?authSource=admin&retryWrites=false
      - JWT_SECRET=${SECRET_TOKEN:-supersecret}
      - JWT_EXPIRATION_MS=315360000000  # 10 years - non-expiring token
    networks:
      - uncovering-history
networks:
  uncovering-history:
    driver: bridge
